### ISSUE TITLE
Первые проблемы

### ISSUE THREAD

**Issue by gfbbkon** [VanStepYT/IndustrialExpansion#1]
Нету трансформатора 512k EU и UV трансформатор получает только до 200k вместо 130k. Это делает самое крутое хранилище бесполезным, так как энергию с него никуда не отправить.
Кстати, о энергохранилищах, 2kkk EU делают эти предметы бесполезными, хотя их большое количество энергии надо как-то передать, поэтому здесь требуется какой-нибудь кабель
И также надо немного изменить регулируемый трансформатор, чтобы он мог принимать новые уровни напряжения

**Comment by VanStepYT** [comment]
1. Добавлен Трансформатор СУН
2. Добавлен Продвинутый Регулируемый Трансформатор
3. В моде уже существует Фотоновый Кабель, Проводящий до Милиона EU
